"use client";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  let pathnameUrl = usePathname();
  // console.log(pathnameUrl);
  // // if (pathnameUrl === "/Dashbord") {
  // //   return <>{children}</>;
  // // }
  return (
    <html lang="en">
      <body className="container px-2 sm:px-5  m-auto bg-black text-white ">
        {pathnameUrl === "/" ? (
          // return(

          <div>{children}</div>
        ) : (
          // <div>
          //   <div className="flex items-center justify-between mt-9 ">
          //     <h1 className="font-bold text-3xl font-mono ">GM - Abdou</h1>
          //     <ul className="flex items-center justify-between gap-6 mr-5">
          //       <Link href="/">
          //         {" "}
          //         <li className="font-semibold  text-sm text-black/50 text-white  transition cursor-pointer">
          //           Home
          //         </li>
          //       </Link>
          //       <Link href="/blog">
          //         {" "}
          //         <li className="font-semibold  text-sm text-black/50 text-white  transition cursor-pointer">
          //           blog
          //         </li>
          //       </Link>
          //     </ul>
          //   </div>
          //   {/*
          //   {children} */}
          // </div>
          <div>
            {" "}
            <div className="flex items-center justify-between mt-9 ">
              <h1 className="font-bold text-3xl font-mono ">GM - Abdou</h1>
              <ul className="flex items-center justify-between gap-6 mr-5">
                <Link href="/">
                  {" "}
                  <li className="font-semibold  text-sm text-black/50 text-white  transition cursor-pointer">
                    Home
                  </li>
                </Link>
                <Link href="/blog">
                  {" "}
                  <li className="font-semibold  text-sm text-black/50 text-white  transition cursor-pointer">
                    blog
                  </li>
                </Link>
              </ul>
            </div>{" "}
            {children}
          </div>
        )}
        {/* {children} */}
      </body>
    </html>
  );
}
