// "use client";
import localFont from "next/font/local";
import "./globals.css";
// import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // let pathnameUrl = usePathname();
  // console.log(pathnameUrl);
  // // if (pathnameUrl === "/Dashbord") {
  // //   return <>{children}</>;
  // // }
  return (
    <html lang="en">
      <body className="container px-5  m-auto bg-black text-white text-white">
        {/* {pathnameUrl === "/Dashbord" ? (
          <div> {children}</div>
        ) : (
          <div>
            {" "}
            <h1>Logo</h1>
            <ul>
              <li>Home</li>
              <li>About</li>
            </ul>
            <div> {children}</div>
          </div>
        )} */}

        <div className="flex items-center justify-between mt-9 ">
          <h1 className="font-bold text-3xl font-mono ">GM - Abdou</h1>
          <ul className="flex items-center justify-between gap-6 mr-5">
            <li className="font-semibold  text-sm text-black/50 text-white  transition cursor-pointer">
              Home
            </li>
            <li className="font-semibold  text-sm text-black/50 text-white  transition cursor-pointer">
              blog 
            </li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
